### ISSUE TITLE
Some papaya pages don't work quite right

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-www#10]
mod_t2w.html and mod_t1w.html are examples that don't work. However, acq_aomovie.html works just fine.

I'm not quite sure what's up.

---Alex

**Comment by hanke** [comment]
Working papaya commit:  a2f3fd1613859f1c8faff33fa44e66c4017706db

**Comment by Alexqw** [comment]
@hanke Hmm, that commit doesn't fix it for me. Maybe my data files are just messed up (I can't generate many of them)...

---Alex

**Comment by hanke** [comment]
Let's ignore this for now -- I am pretty sure it won't be an issue in the end.

**Comment by aqw** [comment]
This is obsoleted by the move to NeuroVault iframes.
