### ISSUE TITLE
determine fate of contest pages

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-www#45]
All subpages were dropped during the overhaul of the website. However, the contest is a pretty unique event, and it would be ideal if we could keep those pages around, for posterity.

The related pages are:

- [challenge.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/pages/challenge.rst)
- [reallifecognition_contest_results.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/Articles/reallifecognition_contest_results.rst)
- [reallifecognition_contest_aftermath.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/Articles/reallifecognition_contest_aftermath.rst)
- [contest_fuseisc.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/Studies/contest_fuseisc.rst)
- [contest_findforrestnetworks.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/Studies/contest_findforrestnetworks.rst)
- [contest_surfacebased_2ndorder_similarity.rst](https://github.com/psychoinformatics-de/studyforrest-www/blob/69be8984a2c72ed2d3f691087fe177dcc382e0e0/content/Articles/contest_surfacebased_2ndorder_similarity.rst)

The pages written by us:
- `challenge.rst`: the original announcement. This was taken down and marked as 410 Gone.
- `reallifecognition_contest_results.rst`: announcement of the winners. High value. However, it links to multiple non-contest-related articles/studies on the site.
- `reallifecognition_contest_aftermath.rst`: post mortem of the study. It is written more like a blog post, and links to non-contest-related articles/studies on the site.

In my opinion, `reallifecognition_contest_results.rst` should be kept. We edit it to remove the links and improve the language. The initial `challenge.rst` can be restored if we'd like, and similarly edited. The post mortem can be dropped.

The pages written by the the winners:

- `contest_fuseisc.rst`: Has a handful of images and a few Matlab source files. It also links to a small collection of `nii.gz` files totaling 26 MiB.
- `contest_findforrestnetworks.rst`: Has a few images and single Matlab source file.
- `contest_surfacebased_2ndorder_similarity.rst`: Has a video (14 MiB), zip archive (186 MiB)

The content here is easy: we change none of it. The problem is where to host the data. The images, movie, and scripts should all be stored in the git repo. But the remaining files total to ~212 MiB. The most viable solution I see is to host those elsewhere. Though it might be worth unpacking them, so see if there's easy compression gains to be had.

GitHub's limit for file-size in repositories is 100 MiB.

**Comment by mih** [comment]
The main outcome of the competition made it into a proper paper: https://onlinelibrary.wiley.com/doi/epdf/10.1002/hbm.23549 (which seems missing from the old publication list, didn't check the new one). With that being added to the list, I would be OK with dropping all that content entirely, and hand it over to http://web.archive.org/web/20200127035909/http://studyforrest.org/reallifecognition_contest_results.html

**Comment by aqw** [comment]
Thanks for taking a look. :-)

I have confirmed that the paper is in the new publication list.

So it is decided: no need to uplift the old pages. And we will all remember to donate to the Internet Archive, because those people make civilization possible.
