### ISSUE TITLE
two broken publication links

### ISSUE THREAD

**Issue by aqw** [psychoinformatics-de/studyforrest-www#49]
- https://www.doi.org/https://proceedings.neurips.cc/paper/2015/file/b3967a0e938dc2a6340e258630febd5a-Paper.pdf
- https://www.doi.org/https://arxiv.org/abs/1606.02627v1

@adswa When you have the time, can you take a look at why the tool is generating these URLs?

**Comment by adswa** [comment]
will do, thanks for the report!

**Comment by adswa** [comment]
The problem exists because of two things: These two papers do not have a doi and I entered their url manually into the database, and my tool tries to build doi urls to get the most persistent references possible. I'll try to make the tool a bit more flexible.
